name: lili

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache tools
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            autoit-v3-setup.exe
            SciTE4AutoIt3.exe
            C:\Program Files (x86)\AutoIt3\SciTE\Au3Stripper
          key: v2
      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfLO https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe `
            -sSfLO https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe `
            -sSfLO https://www.autoitscript.com/autoit3/scite/download/Au3Stripper.zip
          Expand-Archive Au3Stripper.zip "${env:ProgramFiles(x86)}\AutoIt3\SciTE\Au3Stripper"
      - name: Install tools
        run: |
          Start-Process autoit-v3-setup.exe -ArgumentList /S -NoNewWindow -Wait
          Start-Process SciTE4AutoIt3.exe -ArgumentList /S -NoNewWindow -Wait
      - name: Zip Tools Folder
        run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\LinuxLiveUSBCreator
           Compress-Archive -Path .\tools -Destination .\tools.zip -force
      - name: Compile
        run: |
          cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\LinuxLiveUSBCreator\sources\LiLi\
          Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /NoStatus /prod /in LiLi USB Creator.au3" -NoNewWindow -Wait
          sha256sum -b WhyNotWin*.exe > checksums.sha256
      - name: Rename and Aggregate Files
        run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
           mkdir build
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\LinuxLiveUSBCreator
           $ver= git rev-list --count HEAD
           Remove-Item C:\"Program Files (x86)"\AutoIt3\Aut2Exe\LinuxLiveUSBCreator\tools -Recurse -Force
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\LinuxLiveUSBCreator\Sources\LiLi
           Move-Item "LiLi USB Creator.exe" C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           Rename-Item -Path "LiLi USB Creator.exe" -NewName LiLiUSBCreator-2.10dev$ver.exe
      - uses: actions/upload-artifact@v2
        with:
          name: lili
          path: |
            Linux*.exe
            checksums.sha256
          if-no-files-found: error
      - name: Zip package
        if: startsWith(github.ref, 'refs/tags/')
        run: 7z a LinuxLiveUSBCreator.zip Linux*.exe checksums.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Linux*.exe
            LinuxLiveUSB.zip
            checksums.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
